# Client Mode - `direct` or `proxy`
# log is not use toml config
mode = "log"

## Direct Mode
[DirectClientConfig]
ConfigUrl = ""
FullUserName = ""
Password = ""
SysUserName = "root"
SysPassword= ""


## ODP Mode
[OdpClientConfig]
OdpIp = ""
OdpRpcPort = 0
FullUserName = ""
Password = ""
Database = ""


# Normal Configuration
[ConnConfig]
PoolMaxConnSize = 1
ConnectTimeOut = 1000
LoginTimeout = 1000


[TableEntryConfig]
RefreshLockTimeout = 4000
RefreshTryTimes = 3
RefreshIntervalBase = 100
RefreshIntervalCeiling = 1600


[RouteMetaDataConfig]
RefreshInterval = 60000
RefreshLockTimeout = 8000

[RsListConfig]
LocalFileLocation = ""
HttpGetTimeout = 1000
HttpGetRetryTimes = 3
HttpGetRetryInterval = 100


[ExtraConfig]
OperationTimeOut = 10000
LogLevel = "info"
EnableRerouting = false
MaxConnectionAge = 0
EnableSLBLoadBalance = false

[LogConfig]
LogFileName = "./"
SingleFileMaxSize = 256   ## MB
MaxBackupFileSize  = 10   ## 0 is not delete
MaxAgeFileRem = 30        ## 30 day
Compress = false          ## default not
SlowQueryThreshold = 40   ## ms
